### PR TITLE
doc: add decodeAbiParameters examples

### PR DESCRIPTION
**Pull request by izayl**
add examples to show how to use `getStorageAt` and `decodeAbiParameters` to decode slot data

---

## PR-Codex overview
This PR adds examples for decoding ABI parameters in Viem.

### Detailed summary
- Added two code examples for decoding ABI parameters
- Examples demonstrate decoding of uint256 and mapping of uint256
- Examples use `decodeAbiParameters` function from Viem library
- Examples use `createPublicClient` function to interact with Ethereum network
- Examples use `http` transport and `mainnet` chain from Viem library

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by jxom** [comment]
@izayl – is this ready for review?

**Comment by izayl** [comment]
@jxom wait me add two more example, soon today.

**Comment by izayl** [comment]
@jxom I'm planing to contribute to create a examples website like https://solidity-by-example.org/ to show/run online use case about viem, include examples in https://github.com/wagmi-dev/viem/tree/main/examples and more real word case example, do you have some advice?

**Comment by tmm** [comment]
> 

@izayl sounds great! I'd start small with a handful of foundation examples. Can link to it too.

**Comment by jxom** [comment]
Closing this PR as it is becoming stale. @izayl: can you re-open as a new PR when you have finalized what you wanted to add in?

**Pull request closed without merging**
