### PR TITLE
chore: add `packageManager` field

### PR DESCRIPTION
**Pull request by sxzz**
to pin `pnpm@7`

---

## PR-Codex overview

> The following files were skipped due to too many changes: `pnpm-lock.yaml`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by fubhy** [comment]
Just wondering... Should we pin this to 8.3.1 already?

**Comment by fubhy** [comment]
Great. Looks good imho.

**Review by fubhy — APPROVED** [review]

**Review by tmm — COMMENTED** [review]
Would be nice to make sure pnpm versions match in the [CI workflows](https://github.com/wagmi-dev/viem/blob/main/.github/workflows/main.yml#L19) via `matrix.pnpm-version`.

Hopefully we can just use Corepack with the workflows [some day](https://github.com/actions/setup-node/pull/651).

**Comment by sxzz** [comment]
@tmm Done. `pnpm/action-setup` now will read [packageManager field in the package.json](https://nodejs.org/api/corepack.html)

https://github.com/pnpm/action-setup#version

**Review by tmm — APPROVED** [review]

**Pull request merged**
