### PR TITLE
Make `chainOverride` parameter optional in `WriteContractParameters`

### LINKED ISSUE #891: Value is required on write contract options
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.9

### Current Behavior

Hello,

I am trying to put a gasLimit on a write function using the result of a getContract(). and am confused why I have to include `value` when the documentation says it is optional.

The error I am getting is
```
Argument of type '{ gas: bigint; }' is not assignable to parameter of type '{ account?: `0x${string}` | Account | undefined; chain?: Chain | null | undefined; type?: "legacy" | undefined; gas?: bigint | undefined; nonce?: number | undefined; value: bigint; ... 4 more ...; dataSuffix?: `0x${string}` | undefined; } | { ...; } | { ...; } | undefined'.
  Property 'value' is missing in type '{ gas: bigint; }' but required in type '{ account?: `0x${string}` | Account | undefined; chain?: Chain | null | undefined; type?: "eip1559" | undefined; gas?: bigint | undefined; nonce?: number | undefined; value: bigint; ... 4 more ...; dataSuffix?: `0x${string}` | undefined; }'
``` 

My versioning is

   "viem": "^1.2.9",
    "wagmi": "^1.3.7",

### Expected Behavior

value to not be required in options param as following the documentation:

https://viem.sh/docs/contract/writeContract.html

### Steps To Reproduce

```typescript
 const { data: walletClient } = useWalletClient();
 const publicClient = usePublicClient();

const exampleContract = getContract({
    address,
    abi,
    publicClient,
    walletClient,
 })
 
 const gas = await exampleContract.estimateGas.addLiquidity([1])
 
 exampleContract.write.addLiquidity([1], {gas: gas * BigInt(1.5)})
 
``` 

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Nazeeh21**
Closes #891.
Made the `chainOverride` parameter optional in `WriteContractParameters` in `writeContract.ts` file. 

Pls have a look and lmk if any changes are required

---

## PR-Codex overview
This PR focuses on adding support for a `value` parameter in the `writeContract` function. 

### Detailed summary
- Added a `value` parameter to the `writeContract` function.
- If the `value` parameter is not provided, it is set to `undefined`.
- The `value` parameter is included in the `sendTransaction` call.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by tmm** [comment]
Think we want to make payable `value` optional without changing any of the runtime parameters (e.g. adding `chainOverride` parameter). It should happen at the type-level.

**Comment by Nazeeh21** [comment]
Ohh okay! Will try doing it that way

**Comment by Nazeeh21** [comment]
I have updated the `WriteContract` params at the type-level, pls have a look and lmk if any changes are required.

**Comment by jxom** [comment]
Thanks for the PR! We ended up fixing this in #1040.

**Pull request closed without merging**
