### PR TITLE
feat: add verifyAbi api

### PR DESCRIPTION
**Pull request by izayl**
### Focus of this PR:
This PR adds a new `verifyAbi` API to the `viem` library.

### Detailed summary:
- Added a new `verifyAbi` API to verify that the ABI matches the contents of the bytecode.
- Added a new `AbiNotFoundOnBytecodeError` error class.
- Updated the documentation with usage examples for `verifyAbi`.
- Added tests for `AbiNotFoundOnBytecodeError` and `verifyAbi`.

> The following files were skipped due to too many changes: `src/utils/abi/verifyAbi.test.ts`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by izayl** [comment]
@jxom can u help me review this PR if u have time, I not sure what effect as some test failed

**Comment by jxom** [comment]
Really appriciate this PR! I am a bit hesitent to add extra API surface if it's not a widely used use-case. But I'm wondering if this is better off as a copy-paste kinda guide in the Viem docs?

**Comment by izayl** [comment]
agree with that, maybe I can move this part to examples?

**Comment by jxom** [comment]
@izayl – Yes! Sounds great! I'll close this one off for now, but happy for you to create another PR with the example.

**Pull request closed without merging**
