### PR TITLE
wip – feat: getEnsTextRecord

### PR DESCRIPTION
**Pull request by kesar**
In order to match ethers getAvatar() implementation

discussion: https://github.com/wagmi-dev/viem/discussions/255

### CODE REVIEW

**Comment by jxom** [comment]
Thanks for the PR! Agree that having an abstraction to fetch an ENS avatar will definitely be required in viem. 

From the stance of viem's vision of "atomic" Actions, this PR is fantastic. However, I feel like 95% of the consumers who will use this function will also want to resolve the image URL from: base64 metadata, ERC `"eip155:1/"` strings, IPFS url, SVGs, etc etc... Ethers does [some work](https://github.com/ethers-io/ethers.js/blob/main/src.ts/providers/ens-resolver.ts#L350-L484) internally for this, however, it's not "complete". I feel like the [ens-avatar repository](https://github.com/ensdomains/ens-avatar) does a much better job at doing this. 

I'd still like to go ahead with this PR, and instead repurpose it to generically support text record resolution instead. What do you think of making this `getTextRecord` instead of `getAvatar`?

**Comment by kesar** [comment]
> Thanks for the PR! Agree that having an abstraction to fetch an ENS avatar will definitely be required in viem.
> 
> From the stance of viem's vision of "atomic" Actions, this PR is fantastic. However, I feel like 95% of the consumers who will use this function will also want to resolve the image URL from: base64 metadata, ERC `"eip155:1/"` strings, IPFS url, SVGs, etc etc... Ethers does [some work](https://github.com/ethers-io/ethers.js/blob/main/src.ts/providers/ens-resolver.ts#L350-L484) internally for this, however, it's not "complete". I feel like the [ens-avatar repository](https://github.com/ensdomains/ens-avatar) does a much better job at doing this.
> 
> I'd still like to go ahead with this PR, and instead repurpose it to generically support text record resolution instead. What do you think of making this `getTextRecord` instead of `getAvatar`? We are planning to look into a more complete avatar solution very soon as we will need this for the wagmi v1 upgrade. If you also want to take that on, happy to chat about it.

sure, I had a similar feeling when I was writing the implementation. Gonna work on that and make it more generic 👍🏻 

btw big kudos for the dev experience to contribute, everything worked perfect following the contribution documentation

**Comment by jxom** [comment]
Thanks! Also, this PR is using the ENS Public Resolver. Can we instead use the UniversalResolver? Here is [example usage](https://github.com/wagmi-dev/viem/blob/main/src/actions/ens/getEnsAddress.ts#L60-L96) – we will need to swap out `addr` with `text` instead obviously.

**Comment by kesar** [comment]
fixed using UniversalResolver and made it more generic to support other textRecords.

**Comment by nand2** [comment]
Awesome! Thanks for this, I was looking for this :)

**Comment by jxom** [comment]
Going to close this in favor of #259. Unforunately, there are conflicting implementations here, and we have to chose one. Probably less complicated if we merge #259. Will use the docs in this PR though, so I'll make sure to attribute you as the author of that commit. Thanks so much once again!

**Pull request closed without merging**
