### PR TITLE
Load isomorphic-ws via import rather than async import

### PR DESCRIPTION
**Pull request by brianathere**
### Focus of this PR:
This PR focuses on converting the import of `isomorphic-ws` to a synchronous import.

### Detailed summary:
- Converted `isomorphic-ws` to a synchronous import in `viem` patch.
- Added import statements for `WebSocket` and `MessageEvent` in `rpc.ts`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by jxom** [comment]
Thanks for the PR! Unfortunately, the sync import of `isomorphic-ws` breaks in an Edge Runtime environment: https://github.com/wagmi-dev/viem/pull/375. 

Maybe we can fix this upstream in Node.

**Comment by brianathere** [comment]
I'm sure that can be fixed here as well. Do you have ay repro steps or environment information for where this is failing?

It really shouldn't be an issue, as the isomorphic code is very simple.

**Comment by brianathere** [comment]
Looking at issues, am I right in guessing it was the vercel edge environment where this issue was encountered?

**Comment by brianathere** [comment]
And is it possible they fixed the issue here: https://github.com/vercel/edge-runtime/pull/309

**Comment by jxom** [comment]
Yep, it was Vercel's Edge Runtime. If we can confirm it has been fixed, then am happy to merge this PR!

**Comment by brianathere** [comment]
Related tickets that would be easier to debug with this change:

https://github.com/nodejs/node/issues/44211
https://github.com/nodejs/node/issues/45449
https://github.com/nodejs/node/issues/44219
https://github.com/nodejs/node/issues/43205
https://github.com/nodejs/node/issues/40058

**Comment by brianathere** [comment]
Finally, while true that I don't see an easy path to correct the error, I believe it's better to report the error to the caller than to end the process.

**Comment by brianathere** [comment]
I created a sample project here https://github.com/brianathere/viem and published it via vercel. It works fine with my change.

**Comment by brianathere** [comment]
@jxom can you trigger a deploy to vercel to see if anything else causes an issue? I've confirmed with my sample vercel app that viem can be used in the edge runtime, using webscokets, with my change.

**Comment by jxom** [comment]
Hmm. I'm still getting errors on Edge Runtime: https://test-edge-jxom.vercel.app/

**Comment by jxom** [comment]
I still seem to be having issues with importing on Edge Runtime:

Screenshot 2023-09-01 at 11 40 54 am

**Comment by brianathere** [comment]
> I still seem to be having issues with importing on Edge Runtime:
> 
> Screenshot 2023-09-01 at 11 40 54 am

Thank you, where can I see that log? I don't see that in the failing test. I'm happy to fix it if I can figure out the repro.

**Comment by jxom** [comment]
Actually, this was probably because we should be using the default export. Retesting now.

**Review by jxom — APPROVED** [review]

**Pull request merged**
