### PR TITLE
feat: tree-shakeable client types

### PR DESCRIPTION
**Pull request by tmm**
Allows `Client` type to be used with public and wallet actions for maximum tree shakeability.

```ts
const client = createClient({
  chain: mainnet,
  transport: http(),
})
const res = await readContract(client, {
  abi: seaportAbi,
  address: '0x',
  functionName: 'name',
})
```

Doesn't work with test actions right now since they have a more complex type set up (e.g. `mode`).

### Summary
🧪🔄🤝

This pull request enhances the compatibility and flexibility of the actions module by refactoring the functions to accept different types of clients from the `clients` module. It also adds tests for the actions module using the `vitest` framework. It affects the files in the `src/actions` directory and the new file `src/actions/actions.test-d.ts`.

> _`Client` type expands_
> _Actions work with many kinds_
> _Autumn of refactor_

### Walkthrough
*  Add tests for the actions module using the `vitest` framework in a new file `actions.test-d.ts` ([link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-9be828c79a3e9cb54e0a72ca39bc5933f5b52f961fcef1647d0b15aa2fe09333R1-R87))
*  Refactor the actions module to accept more generic `Client` types instead of only `PublicClient` or `WalletClient` types, to make the actions more flexible and compatible with different types of clients ([link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-558e56c3ceef347752e66c0124345f4d02234267e325955259ecffc1abfa7b2bL1-R4), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-558e56c3ceef347752e66c0124345f4d02234267e325955259ecffc1abfa7b2bL35-R35), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-17ff3b62185b07d342d7707332e62fec346aa1eb8dbb0c770b4621dba08081f2L1-R1), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-17ff3b62185b07d342d7707332e62fec346aa1eb8dbb0c770b4621dba08081f2L19-R19), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-428143195eda69a05b80e12e8f52b2ff65180e206b076f4700d9e0c9eee00d70L1-R1), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-428143195eda69a05b80e12e8f52b2ff65180e206b076f4700d9e0c9eee00d70L35-R35), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-6d2c0a21a207456eda46155682c095538a26ee6600634a2f21ee5d998223c72dL1-R1), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-6d2c0a21a207456eda46155682c095538a26ee6600634a2f21ee5d998223c72dL22-R22), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-75dbee1a05e5b8710a64fd8da1e94e9544bcf870299d83bea3554a7cf85ec992L1-R1), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-75dbee1a05e5b8710a64fd8da1e94e9544bcf870299d83bea3554a7cf85ec992L42-R42), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-545e9b42d9b9f1f196aa9e12769154c35389844ad9f9d20a86dbcecce9c38e7aL1-R1), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-545e9b42d9b9f1f196aa9e12769154c35389844ad9f9d20a86dbcecce9c38e7aL52-R52), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-bce6a737c5425184b59b0ba5170f9a123e954dfd0b19bc6d950a1a48e63989c1L1-R1), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-bce6a737c5425184b59b0ba5170f9a123e954dfd0b19bc6d950a1a48e63989c1L7-R7), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-47e3c49e8adfd745a0384baee8a6f5c3a1afc04ac0d2d553e343915f668e8a48L2-R2), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-47e3c49e8adfd745a0384baee8a6f5c3a1afc04ac0d2d553e343915f668e8a48L60-R60), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-ded6f6275e27ded192fd123043e47172886f1bc3d21a75cb54fc88e73675463cL2-R2), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-ded6f6275e27ded192fd123043e47172886f1bc3d21a75cb54fc88e73675463cL74-R74), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-938d780d4707c767e5396a5bb54909d972ec61e867964acd9d1b4834cd47cd84L3-R3), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-938d780d4707c767e5396a5bb54909d972ec61e867964acd9d1b4834cd47cd84L29-R29), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-36f01eca8a5ff7e486002007e5e9fadbef91a2baabd7a6553b346431ecd1f376L1-R1), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-36f01eca8a5ff7e486002007e5e9fadbef91a2baabd7a6553b346431ecd1f376L27-R27), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-0299f67471966ca93786d9ff0abba9ea4b59fb59314ed2216e37e5a1c3d37561L1-R1), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-0299f67471966ca93786d9ff0abba9ea4b59fb59314ed2216e37e5a1c3d37561L22-R22), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-324fb45a9dcceb5fc4e4c6f019a3fd6e727f55f581ca4112694eb5b9a065827cL1-R1), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-324fb45a9dcceb5fc4e4c6f019a3fd6e727f55f581ca4112694eb5b9a065827cL30-R30), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-0d90fc924984d5585cd474ec35c98b162c5477c596dc588b5ac5b116297e04c9L1-R1), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-0d90fc924984d5585cd474ec35c98b162c5477c596dc588b5ac5b116297e04c9L21-R21))
*  Update the order of the generic type parameters in the `getContract` function and the `GetContractParameters` type to match the order of the `Client` type, which is `TChain`, `TAccount`, `TTransport`, for consistency and ease of use ([link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-a1828dde770bf4dff63ad714b898138f40c37f278f6c91500612a9174ddb8c04L48-R54), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-a1828dde770bf4dff63ad714b898138f40c37f278f6c91500612a9174ddb8c04L204-R212), [link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-a1828dde770bf4dff63ad714b898138f40c37f278f6c91500612a9174ddb8c04L220-R222))
*  Update the order of the generic type parameters in the `createPendingTransactionFilter` function to match the order of the `Client` type, which is `TChain`, `TTransport`, for consistency and ease of use ([link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-64e44cdb806ccbbea7ae772237c22103d071f919dcf4b3349c9bd61e46818cb3L7-R10))
*  Add a comma after the `trim` import from the `utils` module in the `getEnsAddress` file to follow the code style and formatting rules ([link](https://github.com/wagmi-dev/viem/pull/314/files?diff=unified&w=0#diff-558e56c3ceef347752e66c0124345f4d02234267e325955259ecffc1abfa7b2bL12-R12))

### CODE REVIEW

**Comment by roninjin10** [comment]
What does tree-shakable types even mean?   Aren't all types tree shaken essentially both in .js and .d.ts files?

**Comment by tmm** [comment]
> What does tree-shakable types even mean? Aren't all types tree shaken essentially both in .js and .d.ts files?

Yeah, the types aren't tree-shakeable. This PR allows you to create a plain `Client` and use it with actions.

```ts
const client = createClient({ transport: http() })
const res = await readContract(client, {
  abi: seaportAbi,
  address: '0x',
  functionName: 'name',
})
```

Right now, only ["decorated"](https://github.com/wagmi-dev/viem/pull/77) clients can be used with actions. By allowing folks to also use `Client`, no decorated actions make it into the final bundle.

**Comment by roninjin10** [comment]
oh sick!   Yea I remember when I first looked at viem this action(client, ...params) api was all I saw and I don't think decorated clients existed.    Was very surprised at the time you went the route of slightly more ergonomic ux for some % of devs with client.action syntax over the hyper optimized code splitting based on how ya'll seemed to be thinking about viem

**Comment by tmm** [comment]
Closing since this is stale. Will open in follow-up.

**Pull request closed without merging**
