### PR TITLE
feat: add chain url avaliable check

### PR DESCRIPTION
**Pull request by izayl**
### Focus of the PR:
This PR focuses on adding chain checking functionality and updating configuration files.

### Detailed summary:
- Added `tsconfig.json` to include the `test/src` directory for local development and type checking.
- Added `test/tsconfig.json` with compiler options for `bun-types` and path mapping.
- Updated `src/utils/promise/withTimeout.ts` to make the `errorInstance` parameter optional.
- Added `github/workflows/chaincheck.yml` for checking chains in the CI workflow.
- Updated `package.json` to include a `chaincheck` script.
- Added `test/chains/check.test.ts` for testing chain URLs and block explorers.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by izayl** [comment]
seems not suitable to check it on Actions, as it has maximum only 5 min runtime

**Review by jxom — COMMENTED** [review]
Looks good! Instead of running this in a Bun script, do you think we could just run them as Bun tests? 

This means we can get rid of the `for` loop, console logs, etc.

**Comment by izayl** [comment]
looks pretty
image

**Comment by izayl** [comment]
should we use snapshot test, to make sure the new added chain is available

**Pull request merged**
