### PR TITLE
Add re-initialization logic for event filters

### PR DESCRIPTION
**Pull request by jaxernst**
Here's my proposal to address #836.  Filters can timeout or get into a bad state where reinitialization is necessary to continue getting filter changes on the polling interval. This request adds fallback reinitialization, so if 'getFilterChanges' fails repeatedly, it will attempt to recreate the filter.

---

### Focus of the PR:
This PR focuses on adding filter reinitialization logic for `watchContractEvent` and `watchEvent` when a filter has been uninstalled.

### Detailed summary:
- Added filter reinitialization logic for `watchContractEvent` and `watchEvent` when a filter has been uninstalled.
- Imported `InvalidInputRpcError` in `watchEvent.ts` and `watchContractEvent.ts`.
- Added error handling and filter reinitialization logic in `watchEvent.ts` and `watchContractEvent.ts` if a filter has been set and gets uninstalled.
- Added a test case to verify the filter reinitialization logic in `watchEvent.test.ts` and `watchContractEvent.test.ts`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by jxom** [comment]
Instead of checking if the filter has errored n times, maybe we can check the error instead for “filter not found”.

Most nodes support this, examples:
https://github.com/ethereum/go-ethereum/blob/master/eth/filters/api.go#L38
https://github.com/paradigmxyz/reth/blob/f41386d28e89dd436feea872178452e5302314a5/crates/rpc/rpc/src/eth/filter.rs#L447

**Comment by jaxernst** [comment]
> Instead of checking if the filter has errored n times, maybe we can check the error for “filter not found”.
> 
> Most nodes support this, examples: https://github.com/ethereum/go-ethereum/blob/master/eth/filters/api.go#L38 https://github.com/paradigmxyz/reth/blob/f41386d28e89dd436feea872178452e5302314a5/crates/rpc/rpc/src/eth/filter.rs#L447

This does make more sense. I was hesitant to do this because I wasn't sure if "filter not found" was standardized, so I looked a bit further. Every client I've checked returns this error except for Erigon:

Besu: https://github.com/hyperledger/besu/blob/main/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/RpcErrorType.java#L45

Nethermind:
https://github.com/NethermindEth/nethermind/blob/a099f0fe2158b969ca6b81861c5097ecc5f6c0b1/src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs#L553

Erigon:
https://github.com/ledgerwatch/erigon/blob/56934395210c48585ae8d7f77404d7c9b9ba3a30/turbo/jsonrpc/eth_filters.go#L78


Should we still check for this even if not all clients return it?

**Comment by jxom** [comment]
Thought so. Maybe we can keep the current implementation as a fallback, and check the error first?

**Comment by jaxernst** [comment]
Although Erigon doesn't throw a 'filter not found', they do all appear to return a -32000 (Invalid input) error code when the filter isn't found. It looks like Viem already catches these as "InvalidInputRpcError", so might we just reinitialize the filter if we catch an InvalidInputRpcError?

**Comment by jaxernst** [comment]
Implemented this with tests for watchContractEvent and watchEvent

**Review by jxom — APPROVED** [review]
Looks good! Will merge it in soon.

**Pull request merged**
