### PR TITLE
chore: move configuration, script and contract files into dedicated dev folder

### PR DESCRIPTION
**Pull request by Raiden1411**
## PR-Codex overview
This PR updates and moves config files into a dedicated `dev` directory. Notable changes include:

- New `dev` directory with updated file paths
- Added `.vscode` and `.idea` directories
- Added `cache` and `out` directories
- Added `lib/ds-test` submodule
- Updated file paths in various configuration files
- Added new contracts and libraries, including `CompilationTest`, `CompilationScript`, and `StdError`

> The following files were skipped due to too many changes: `dev/contracts/lib/forge-std/src/StdError.sol`, `src/_test/utils.ts`, `dev/contracts/lib/forge-std/src/Test.sol`, `dev/contracts/lib/forge-std/LICENSE-MIT`, `dev/contracts/lib/forge-std/src/StdMath.sol`, `dev/scripts/utils/utils.ts`, `dev/contracts/lib/forge-std/src/Base.sol`, `dev/contracts/lib/forge-std/src/interfaces/IMulticall3.sol`, `dev/contracts/lib/forge-std/src/interfaces/IERC20.sol`, `dev/contracts/lib/forge-std/.github/workflows/ci.yml`, `dev/contracts/lib/forge-std/test/StdError.t.sol`, `dev/scripts/utils/caller.ts`, `dev/contracts/lib/forge-std/src/StdInvariant.sol`, `package.json`, `dev/contracts/lib/forge-std/src/StdJson.sol`, `dev/contracts/lib/forge-std/lib/ds-test/demo/demo.sol`, `dev/contracts/lib/forge-std/test/StdChains.t.sol`, `dev/contracts/lib/forge-std/test/StdMath.t.sol`, `dev/scripts/utils/getCurrentLine.ts`, `dev/contracts/lib/forge-std/src/interfaces/IERC1155.sol`, `dev/contracts/lib/forge-std/README.md`, `dev/contracts/lib/forge-std/src/interfaces/IERC721.sol`, `dev/contracts/lib/forge-std/src/StdUtils.sol`, `dev/contracts/lib/forge-std/src/StdChains.sol`, `dev/contracts/lib/forge-std/test/StdStorage.t.sol`, `dev/contracts/lib/forge-std/src/StdAssertions.sol`, `dev/contracts/lib/forge-std/src/StdStorage.sol`, `dev/contracts/lib/forge-std/test/fixtures/broadcast.log.json`, `dev/contracts/lib/forge-std/test/StdCheats.t.sol`, `dev/contracts/lib/forge-std/LICENSE-APACHE`, `dev/contracts/lib/forge-std/test/StdUtils.t.sol`, `dev/contracts/lib/forge-std/src/interfaces/IERC4626.sol`, `dev/contracts/lib/forge-std/lib/ds-test/src/test.sol`, `dev/contracts/lib/forge-std/src/StdCheats.sol`, `dev/contracts/lib/forge-std/src/Vm.sol`, `dev/contracts/lib/forge-std/test/StdAssertions.t.sol`, `dev/contracts/lib/forge-std/lib/ds-test/LICENSE`, `dev/contracts/lib/forge-std/src/console.sol`, `dev/contracts/lib/forge-std/src/console2.sol`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by fubhy** [comment]
Mhm, I can see that `arktype` also uses this pattern. Generally I'd also like to see this as a more widely adopted standard / convention for configuration. Having all that stuff in the root bothers me too, especially with the explosion of tooling & config over the past few years. 

However, I am not sure if I like inventing a bunch of crafty tricks & maintaining those and going against the flow with this. Coming to this repository as a new contributor I'd likely find it harder to navigate things & find which config is coming from where if it's hidden in an unexpected location.

Now, for the status quo to change and the community eventually settling on a shared config location someone has to be the first mover... Not sure if I'd want us to do that tbh. :-/

**Comment by jxom** [comment]
Generally agree with @fubhy. I like to be more pragmatic with directory structure, etc. Config at the root may look overloaded, but it is most discoverable there.

**Comment by Raiden1411** [comment]
@fubhy, @jxom, I see your points. Will close this PR. Hopefully in the future there is a consensus/better way to organize this.

**Comment by tmm** [comment]
Agree with all these points. Hope it's better supported someday or tools have sensible enough defaults so you don't need to configure them :)

**Pull request closed without merging**
